version: '2'
services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    # volumes:
    #   - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test_db
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      # MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes